import { theme } from '@/constants/theme';
import React from 'react';
import {
  AddIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  BankIcon,
  BellIcon,
  BillIcon,
  BrowserIcon,
  BuildIcon,
  CheckEmailIcon,
  CheckIcon,
  CloseIcon,
  cloudIcon,
  CopyIcon,
  DeleteIcon,
  EditIcon,
  EducationIcon,
  EmailIcon,
  ErrorIcon,
  FavoriteIcon,
  FullEditIcon,
  GamingIcon,
  GenerateIcon,
  GoodIcon,
  HealthIcon,
  HelpIcon,
  HideIcon,
  HomeIcon,
  KeyIcon,
  LockIcon,
  LogOutIcon,
  MediaIcon,
  MobileIcon,
  ModerateIcon,
  NamesIcon,
  NewsIcon,
  OtherIcon,
  PhoneIcon,
  PlaneIcon,
  RegenerateIcon,
  ResetIcon,
  SearchIcon,
  secretIcon,
  SecurityIcon,
  serviceIcon,
  SettingsIcon,
  ShoppingIcon,
  ShowIcon,
  SocialMediaIcon,
  StrongIcon,
  ToolsIcon,
  UserIcon,
  VerifiedIcon,
  VeryStrongIcon,
  WeakIcon,
  wifiIcon,
  WorkIcon,
  WorkingIcon,
} from './Icons';

export const icons = {
  add: AddIcon,
  key: KeyIcon,
  generate: GenerateIcon,
  copy: CopyIcon,
  favorite: FavoriteIcon,
  show: ShowIcon,
  hide: HideIcon,
  search: SearchIcon,
  edit: EditIcon,
  delete: DeleteIcon,
  correct: CheckIcon,
  settings: SettingsIcon,
  verified: VerifiedIcon,
  browser: BrowserIcon,
  regenerate: RegenerateIcon,
  mobile: MobileIcon,
  socialMedia: SocialMediaIcon,
  email: EmailIcon,
  bank: BankIcon,
  work: WorkIcon,
  shopping: ShoppingIcon,
  gaming: GamingIcon,
  media: MediaIcon,
  bill: BillIcon,
  education: EducationIcon,
  other: OtherIcon,
  error: ErrorIcon,
  working: WorkingIcon,
  checkEmail: CheckEmailIcon,
  veryStrong: VeryStrongIcon,
  strong: StrongIcon,
  good: GoodIcon,
  moderate: ModerateIcon,
  weak: WeakIcon,
  health: HealthIcon,
  reset: ResetIcon,
  user: UserIcon,
  names: NamesIcon,
  phone: PhoneIcon,
  security: SecurityIcon,
  arrowLeft: ArrowLeftIcon,
  lock: LockIcon,
  service: serviceIcon,
  cloud: cloudIcon,
  wifi: wifiIcon,
  build: BuildIcon,
  airplane: PlaneIcon,
  news: NewsIcon,
  tools: ToolsIcon,
  home: HomeIcon,
  logOut: LogOutIcon,
  help: HelpIcon,
  arrowDown: ArrowDownIcon,
  close: CloseIcon,
  secret: secretIcon,
  bell: BellIcon,
  fullEdit: FullEditIcon,
} as const;

export type IconName = keyof typeof icons;

interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: IconName;
  size?: number;
  color?: string;
}

const Icon: React.FC<IconProps> = ({ name, size = 24, color, ...props }) => {
  const IconComponent = icons[name];
  return <IconComponent size={size} color={color || theme.colors.darkGray} {...props} />;
};

export default Icon;
