[[redirects]]
  from = "/.well-known/assetlinks.json"
  to = "/assetlinks.json"
  status = 200
  force = true

[[redirects]]
  from = "/reset-password"
  to = "/reset-password.html"
  status = 200

[[redirects]]
  from = "/email-validation"
  to = "/email-validation.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200